# Generated by Django 4.2 on 2023-04-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
