# Generated by Django 4.2 on 2023-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_author_avatar_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
