# Generated by Django 4.2.1 on 2023-05-22 05:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, validators=[core.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(blank=True, default=0, upload_to=None),
            preserve_default=False,
        ),
    ]
