# Generated by Django 4.2.1 on 2023-05-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_price_alter_author_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='cover',
        ),
    ]
