# Generated by Django 4.2.1 on 2023-05-28 17:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_lecture_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
